# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Avatar',
            field=models.ImageField(default='avatar/default.png', upload_to='avatar/'),
        ),
    ]
