# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_userinfo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Avatar',
            field=models.ImageField(default='web/static/avatar/default.png', upload_to='web/static/avatar/'),
        ),
    ]
