# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20170629_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='Pic',
            field=models.ImageField(default='web/static/homepicture/default.png', upload_to='web/static/homepicture/'),
        ),
    ]
