# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_place_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='Location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Avatar',
            field=models.ImageField(default='web/static/avatar/default.png', upload_to='web/static/avatar/'),
        ),
    ]
